os: linux
language: shell

services:
  - docker

script:
  - docker-compose run tests
  - docker-compose run docs

deploy:
  provider: pages
  local_dir: htmldocs
  cleanup: false
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: develop
